### ISSUE TITLE
Landscape PDFs appear only as white pages

### ISSUE THREAD

**Issue by TiagoTab** [Alua-Kinzhebayeva/iOS-PDF-Reader#52]
I've tested multiple pdfs and in this version the landscape pages aren't visible.

The page selector shows the number of pages the pdf has, but all appear in white, without any content.

Example PDF: 
https://cdn.yamaha-motor.eu/owner-manuals/Motorcycles/U20SE1.PDF

![img_0171](https://cloud.githubusercontent.com/assets/3111365/24619818/479e8df2-1893-11e7-9be4-399818099b56.PNG)

**Comment by ranunez** [comment]
Thank you for finding this bug @TiagoTab! This is due to the fact the PDF pages happens to have a "Crop Box" size that is not the same as the "Media Box" size. In the meantime, the current workaround is to open up the PDF in Preview and use the "Export as PDF" option, which will export the PDF into a more standard format. Thanks for catching this!

<img width="354" alt="pdfproperties" src="https://cloud.githubusercontent.com/assets/2531425/24778923/0e1f632a-1ae2-11e7-9c00-4227460754b9.png">

**Comment by TiagoTab** [comment]
Saving the PDFs as "US Letter" fixes the problem, thank you for the help 👍
